apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  labels:
    app: web-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - name: backend
        image: ahmed1091/backend:latest
        ports:
        - containerPort: 5001
      - name: frontend
        image: ahmed1091/frontend:latest
        ports:
        - containerPort: 3000
